# Is triggered after a merge to main.
substitutions:
  # Keep the go version in sync with the version used by the tflint image (https://github.com/terraform-linters/tflint/blob/master/Dockerfile)
  # Especially the alpine version is important to create compatible binaries.
  _GO_VERSION: "1.22-alpine3.19"
  _TFLINT_VERSION: "0.51.1"
availableSecrets:
  secretManager:
    - versionName: ${_GITHUB_TOKEN_SECRET_VERSION}
      env: GITHUB_TOKEN
steps:
  - name: "golang:${_GO_VERSION}"
    id: "build-and-test"
    script: go mod tidy && go build && go test -v ./...
    env:
      - GOOS=linux
      - GOARCH=amd64
  - name: "ghcr.io/terraform-linters/tflint:v${_TFLINT_VERSION}"
    id: "verify"
    dir: "manual_tests"
    script: ./run_in_cloudbuild.sh
  - name: "node:20"  # version 20 is LTS, and -alpine and -slim revisions do not include git which is needed
    id: "semantic-release"
    automapSubstitutions: true
    secretEnv:
      - GITHUB_TOKEN
    script: |
      git config --global url."https://user:${GITHUB_TOKEN}@github.com".insteadOf "https://github.com"
      git branch -m ${BRANCH_NAME} # this helps semantic-release to recognize the branch name
      git clone --depth 1 https://github.com/kramphub/semantic-release-configuration.git -b main
      npm install @semantic-release/commit-analyzer@11 @semantic-release/release-notes-generator@12 @semantic-release/github@9
      npx semantic-release@23 --no-ci --extends ./semantic-release-configuration/release.config.cjs
